### ISSUE TITLE
Cursor default back to spatial/temporal band entry fields

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#54]
Would it be possible to get the cursor to jump back to the field where you enter the spatial and temporal bands in the RNRC tool (to save time having to click it back in there to enter the next band)?

**Comment by allisonmuise** [comment]
@SCHNZP 
Unfortunately I do not have control over this behavior. I agree that it would make entry easier but this is part of the built-in behavior of the the Geoprocessing tool interface, which I can't control.
