### ISSUE TITLE
RNRC Tool - updated version fails to run

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#55]
Updated version of the RNRC Tool fails, but older version works, as per attached.
[Beta Testing SCHNZP RNRC Fail Issue.docx](https://github.com/Esri/crime-analysis-toolbox/files/209439/Beta.Testing.SCHNZP.RNRC.Fail.Issue.docx)

**Comment by allisonmuise** [comment]
@SCHNZP : It looks like the script is not in the same relative location to the toolbox. The 'scripts' folder must be stored in the same location as the Crime Analysis Tools.tbx in order for the tool UI to know where it can find the script that it is feeding.

Can you send me a screenshot of Windows Explorer showing the location of the tbx and scripts folder?

**Comment by allisonmuise** [comment]
@SCHNZP : I just submitted a fix for another issue with the classification tool that would have caused an error further down the line.

**Comment by SCHNZP** [comment]
Thanks! Resolved by putting all the toolboxes and scripts folders in the same folder. I have successfully run the latest update of the RNRC tool too.

**Comment by allisonmuise** [comment]
great!
