### ISSUE TITLE
Same day NRs both classed as NR, no originator

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#56]
Ran the RNRC Tool on the Naperville dataset with parameters same as Spencer’s Introduction document, produced the same summary statistics and when mapped looked the same as Spencer’s ‘ArcMapExample’ mxd. But when I applied the same symbology based on “unique values, many fields” combining classification plus temporal band (as per screenshot) to both our mxds this showed pairs/groups of NRs which:
-	Don’t appear to have any originators
-	Have two (stacked) connections linking them.
Symbol levels were set such that the smaller black O dots will appear on top of (without occluding) the larger R or NR dots. Labelling the points with their offence dates showed that these NR-NR pairs are pairs of nearby offences which have the same offence date – meaning the tool can’t distinguish which is the originator and which is the NR and labels them both as NR. This will affect the counts and proportions – overcounting the NRs and undercounting the originators.

![image](https://cloud.githubusercontent.com/assets/18314779/14374487/6461c666-fdaa-11e5-86e1-0768d5e2a52c.png)

**Comment by SCHNZP** [comment]
Further thoughts... I would favour one of the same day NRs to be classed as an originator but I don't have a solution as to how to determine which should be which. I'm not sure how Jerry Ratcliffe's Near Repeat Calculator dealt with this issue but it might shed some light? The output from the NRC has two binary columns: Originator Y/N and Near Repeat Y/N, so it was possible for an incident to be classed as both an NR and an O but I think that would only have occurred when it was the middle incident in a chain of 3 incidents: O-->NR which is also an O for the next --> NR. Once I get the NRC onto the laptop I am using to test this I will run the same data through the NRC and see how it deals with the same-day NR pairs.

**Comment by allisonmuise** [comment]
@SCHNZP : Chris and I noticed this as well. I've updated the scripts with one possible solution. Could you take a look and see if the results make sense? Essentially, it will only create one link between two features. The direction it comes across first determines which incident is O and which is NR.

**Comment by SCHNZP** [comment]
Thanks. I have run the updated version and this solution works to ensure there's an O for each NR in those same day pairs. It isn't 100% consistent with the Ratcliffe NRC in determining which is O and which is NR for the same day offences. Oddly, sometimes they match, sometimes the Ratcliffe NRC identifies both as NRs, and sometimes what's O in the RNRC is the NR in the Ratcliffe NRC and vice versa. A few examples shown in the screenshot (grey/purple being O/NR in the Ratcliffe NRC layer and red/blue shades being O/NR in the RNRC layer).
![image](https://cloud.githubusercontent.com/assets/18314779/14413603/03ba9056-ffd3-11e5-8daa-d48a4654892d.png)

**Comment by SCHNZP** [comment]
Apologies for the lack of a basemap - juggling working on my laptop that has the tools running but no internet access from the office (to use any basemaps), and my work PC that has internet but not the necessary versions of Arc!

**Comment by allisonmuise** [comment]
No worries about the basemap! Honestly, when focusing so intently on the dots, their colors, and the connecting lines, it's easier (at least for me) to NOT have that extra background detail!

It doesn't surprise me that the GP tool sometimes agrees and sometimes disagrees with the NRC over which is O and which is NR. 

Here is a bit of info on the tool's logic:
The tool builds each connection by sorting all incidents from most recent to oldest using built-in logic to arrange features with the same value. From looking at the results, it seems like this order may be determined by OID value. It then takes each incident in turn and attempts to find a source incident. If a connection between those two features was already established, the tool moves on to the next incident without saving the new connection information. Thus, the connection that gets saved is dictated by which incident gets processed first.

I assume the NRC is doing something similar, but if the connections the NRC is drawing make more sense than the connections drawn by the GP tool, I can adjust the logic accordingly.

**Comment by SCHNZP** [comment]
Cool. I think that since there's no actual temporal clue to go on when it's same day it doesn't matter too much what the logic is that determines O or NR. What you describe, which is pretty arbitrary/random, actually makes more sense, I think, than a rule that says 'always make the westernmost point the O' which could skew one's interpretation towards thinking offenders always move in a west-east direction at first glance if you didn't know there was a rule dictating that.

**Comment by allisonmuise** [comment]
@SCHNZP 
OK - script has been updated. Instead of moving on immediately when it finds a duplicate connection, it first has another look around to see if there is another nearby incident that meets the criteria. If there is, it tries to build a connection to it. If that one is a duplicate as well, it looks again until there are either no other possibilities, or it finds a valid option. Please test! This should solve the issues with chains with no O and with missing connections between incidents.

**Comment by allisonmuise** [comment]
Closing - tool now draws connections between all nearby features.
