### ISSUE TITLE
NRs not showing up as NRs/connection criteria and visualisation

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#59]
I think I have found a few examples where NRs haven't been picked up. This is from running the most recent updated tool with the Naperville data but one of the examples appeared with the original tool too.Based on the dates (shown as labels) I think there should be connector lines as shown as dashed red lines below:
![image](https://cloud.githubusercontent.com/assets/18314779/14414448/3a0868fe-ffe7-11e5-96f6-ee56ac21dc24.png)

In the topmost instance, there was a connector there when I used the original tool but now not. In the bottom example, there isn't a connector in either instance.

To work out why that might be the case I'm also trying to understand what the criteria are for connecting a given O to an NR. It looks like the rule for determining which dots to join is something like: draw between an NR and its earliest-in-time originator (since NRs can have multiple originators) but then I can see exceptions to that. Likewise it's not: draw the line between an NR and its closest-in-time originator, although I can see instances of that and exceptions to it. Whatever the criteria, is it the same criteria used to populate the data attribute table "origin" field (ie the connection is between the NR and whichever of its originators is allocated as the "origin" point)?

While it's useful to be able to see a cluster of NRs "fan out" from a common original/earliest originator (which they are all NRs of but also are subsequent Os and NRs of each other), which is what the current method seems to be doing (mostly), I would also find it useful to be able to see the connections as a chain or sequence linking the offences in chronological order. It's something one of the analysts I was training last year raised and I've not been able to find a quick way of doing it with existing functionality. One option is using the CrimeAnalyst Sequencing tool (draws lines joining the dots in sequence) but you'd have to do each little NR cluster at a time, very manual. Would it be possible to offer an option of both ways of defining/visualising what gets connected to what, to run it for the whole dataset at once? Either as a check box when entering the parameters or automatically creating two connection feature classes, one of each type.

**Comment by allisonmuise** [comment]
@SCHNZP : Could you email me the graphic you attached above? amuise at esri.c o m
The compressed graphic is too fuzzy for me to read the date labels. Also, what is the spatial distance between the points, and what were the maximum spatial and temporal bands when the connections were created?

The connection criteria are:

Given a list of spatial bands A, B, and C where C is the largest and A is the specified repeat distance, and
Given a list of temporal bands X, Y, and Z where Z is the largest:

For each incident, from youngest to oldest:
1) Create a temporary layer of all other incidents that happened between the date of the current incident (inclusive) and up to Z days before that date.

2) Find the incident in this temporary layer that happened nearest (in space) to the current incident, searching a maximum distance of C

3) If a source incident is found, save the ID of the source incident in the attributes of the current incident and create a connecting line using the coordinates of the two incidents.

To answer your other question, you could connect all incidents in order of date using the [Points to Line tool](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/points-to-line.htm). Specifying the date field for the Sort Field parameter should connect them in chronological order.

**Comment by allisonmuise** [comment]
@SCHNZP : Great catch! You've found a flaw in the tool's logic. I need to find a way to find the 2nd closest incident when the actual closes causes a duplicate connection. I'll let you know once there is an update posted.

**Comment by SCHNZP** [comment]
Thanks. I have emailed you the screenshot. The maximums were 1500 ft and 21 days. The top line is 933 ft and the bottom line is 504 ft.

Ok so the way I understand the criteria is that it's seeking the shortest connection distance wise, irrespective of temporal proximity so long as it's within Z days.

I think I would find it more useful for each NR to be connected to its earliest in time O (ie "oldest originator") regardless of distance so you can see each NR in a set fanning out from the original 'trigger'. 

Another option is to connect to the "nearest originator" factoring in both time and space ie find the point that minimises the combination of distance and time (but I am guessing that's a lot more complicated to code?)

My other suggestion was connecting to the "latest originator" (i.e. most recent) to create sequential chains. Running the points to lines tool on the whole dataset at once connects all the dots sequentially irrespective of which NR set a given point belongs to, so it doesn't work to just connect within each NR set at once. As with the CrimeAnalyst sequencing tool, one could run in on a given set individually but if there's an opportunity to build an all-at-once option in here just by tweaking the code and adding that option in that would save a lot of time manually running it on each NR set. 

If there were to be multiple originator attributes added, one for each of the different originator types, even if the connection tool only operated on one of them, it would be possible to use the Journey to Crime tool in CrimeAnalyst (or equivalent Geoprocessing Tool if there is one - I've always used CrimeAnalyst so never looked) to generate the connections for the others.

**Comment by allisonmuise** [comment]
@SCHNZP : 

One additional change I'm working on is calculating a field with a value that will group together all incidents and connections that are part of each chain. If I can get that in, you will be able to do points to lines as you are describing. The connecting value could be (and I thing should be) the value of the ultimate originator, which would I think address two of your suggestions above.

What's holding me up currently is the need for each chain to have an O I can trace back from ( #56 ). Once I get that solved, this will be fairly easy. I've created another issue for this: #61

I like the idea of better balance between the time and space components. We did go the easy route, but you are correct that it is very heavily weighted on space. Do you have any suggestions on how we could improve the balance?

**Comment by SCHNZP** [comment]
@allisonmuise 

Great! Re balancing time and space: If you think about the matrix output which has time along the top and space down the side to create the time x space cells, and if for a given NR there are multiple potential Os which would each fall somewhere in that matrix, then the rule could be that the O is the one that is closest in the matrix? So for example if Oa is 100m and 14 days, and Ob is 200m and 6 days then Ob is going to be closer. Maybe a better way of visualising it is like a graph as below and whatever point creates the shortest distance to where the two axis meet at 0,0 would be the closest space-time O. I have no idea how that would translate into code though! Is it the equivalent of creating a score of distance x days and ranking them? Or is it more like pythagoras (as the distance to 0,0 is the hypotenuse)? And the X and Y axis are in different units. The maths is a bit beyond me at that point ;-)

![image](https://cloud.githubusercontent.com/assets/18314779/14473747/aa87072c-014d-11e6-96fe-df16be33a8d8.png)

I were to prioritise which type of O I would find most useful though when thinking about/trying to analyse offender behaviour and the evolution of crime series it would be the "oldest originator" and the "latest originator". That said, from a crime linkage perspective, the "nearest in space-time" may be useful to try and work out if there are any outliers that may be part of the NR set but less close when considering both time and space and so perhaps less likely to be linked (as in part of a same-offender series).

**Comment by allisonmuise** [comment]
@SCHNZP I get where you're coming from, but the challenge with that is still how to weight space vs time. I don't think we can give 1 map unit (could be ft or m) the same weight as 1 time unit (day). In fact, in the graphic above, you've weighted it so that the influence to 4 days is ~= to 100 m.

 I wonder if we could use the user-defined spatial/temporal bands. Do you think 1 spatial band width represents an equal amount of influence as 1 temporal band width?

![2016-04-12 1-31-20 pm](https://cloud.githubusercontent.com/assets/2752195/14474851/d93e6bfe-00b3-11e6-8e63-57d555561f37.png)

**Comment by allisonmuise** [comment]
(FYI: I'm also going to pose this question to Spencer via email)

**Comment by SCHNZP** [comment]
Thanks. Yes I was thinking after posting that how it would be dependent on/skewed by the axis settings.

Whether one band in time = one band in space is a question I was grappling with this afternoon in a different context. I was thinking about calculating a bang to buck ratio to be able to compare for example deployment to 2 days and 200m : x% reduction, 4 days 100m : y% reduction in the sense that if I was a decision maker deciding where/when to deploy, if X and Y were the same, would the ratio be the same - is it more or less resource intensive to add 100m to the patrol or focus of tactics than to add a day. I think the answer is 'depends on the resource and tactics'.

I'll be very interested to hear what Spencer has to say!

**Comment by allisonmuise** [comment]
closing - there isn't a good way to calculate a field for each chain as several chains may now intersect. The original connection issue has been resolved by connecting all nearby features, regardless of which is nearest.
