### ISSUE TITLE
Error 313 - Field Name 10 character limit on shapefiles

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#60]
So I'm now running the RNRC on local data. My usual workflow involves working with shp files rather than geodatabases and feature classes (a legacy issue in terms of how I learnt Arc and also it's been easier for analysts to grasp when teaching them the basics). So I went through my usual process of converting my data to shp files, then went to run the RNRC and came up with:
![image](https://cloud.githubusercontent.com/assets/18314779/14446125/b7411932-00a6-11e6-9d17-6302e9fa07d0.png)

A spot of googling gave me the clue that shp files have a 10 character limit whereas for feature classes it's 64. None of the field names in the input dataset are longer than 10 so I'm figuring that's what's stopping the tool when it tries to add fields like "SpatialBand" which is too long. I guess the question is can those field names be abbreviated to shorter than 10 so the tool will work with shapefiles, or will I need to convert to featureclass to be able to run the tool?

**Comment by SCHNZP** [comment]
Update: converted shp to gdb feature class and the tool ran successfully. 4133 records processed in just under 14 minutes on my ageing laptop.
![image](https://cloud.githubusercontent.com/assets/18314779/14446764/7240c45c-00ad-11e6-9bd1-23d233b10b3f.png)
![image](https://cloud.githubusercontent.com/assets/18314779/14446765/756d7cc4-00ad-11e6-8117-ffe0d78633de.png)

**Comment by SCHNZP** [comment]
And another example: 3591 records, 18 minutes.
![image](https://cloud.githubusercontent.com/assets/18314779/14447004/e574db64-00af-11e6-8d00-3d341c0a9c2d.png)
![image](https://cloud.githubusercontent.com/assets/18314779/14447007/e7bc3eda-00af-11e6-9531-38f9541ff750.png)

**Comment by allisonmuise** [comment]
The tool should run with shapefiles as well as feature classes. Updating those field names is a super easy fix. Would SPACEBAND and TIMEBAND be as clear as SPATIALBAND and TEMPORALBAND? 

If you'd like to test this quickly to make sure there are no other issues with the shapefiles workflow you usually use, open the scripts folder and right-click the incident_classification.py file. Open it in IDLE or another Python IDE. Notepad would work, too. Near the top of the script is a section called '# Added field names' where you can update the values of spatial_band_field (currently SPATIALBAND) and temporal_band_field (currently TEMPORALBAND) to be something shorter. Save the script and re-run the tool from ArcMap/Catalog/Pro and you should get fields with your new names.

**Comment by SCHNZP** [comment]
Easy! That worked :-) Changed to SPACEBAND and TIMEBAND. DISTTOORIG is 10 characters - I left that as it was.

That same 3591 record dataset, same parameters as above, processed in 17m15s this time.

**Comment by allisonmuise** [comment]
Sweet! I updated the field names in my last code update, too, so I'll close this.
