### ISSUE TITLE
RNRC - speeding up parameter entry - suggestion

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#62]
I'm finding if I am running the tool iteratively over similar datasets it's a bit time consuming to re-enter all the parameters each time. Would it be possible to have it keep the last parameters used and have it default to those, then you can just tweak the bands and file names/folders accordingly? Similarly, usually when setting an output file name and folder you just click on the little yellow folder icon and that allows you to browse to the relevant folder and you can click on a file to autopopulate its file name and tweak that instead of manually typing in the file name each time. Would it be possible to have that kind of process instead of the two step Incident Connections Workspace and Feature Class Name?

**Comment by allisonmuise** [comment]
1) re-entering parameters: Unfortunately, re-initializing a GP tool clears all the values, and this isn't something I can control. To save time re-entering, you can access previous parameters from the Results window. I'm sure there is a way to do this in Pro, too, but in ArcMap, expand the Geoprocessing menu and open the Results window. After running a tool in the current session, you'll see the tool and it's results under Current Session. Double-clicking the tool will re-open it with the parameters used to generate that result. When you save the mxd, that result becomes part of the map document history so you can come back and review/use it later. I believe results are stored for 2 weeks by default.

2) Setting outputs: In a custom GP tool I only have two options for file-choosing parameter types - choose a file that already exists, or choose a directory in one parameter and provide the name of a file to create separately.

**Comment by SCHNZP** [comment]
Cool. Thanks for the tip!
