### ISSUE TITLE
running tool with definition query on

### ISSUE THREAD

**Issue by a517dogg** [Esri/crime-analysis-toolbox#63]
I was able to get an error in the prediction zones tool when I had a restrictive definition query on the sample data. below is the error. The error code ("error executing function") is not super helpful; it might be better to have a specific code for when there is not enough data to perform the calculations.

Executing: CalculatePredictionZones Naperville_burglary_sample OFFENSE_DATE YESTERDAY 1300 650 14 7 CUMULATIVE C:\Users\am4337\Desktop\ExampleData.gdb C:\Users\am4337\Desktop\ExampleData.gdb\PredictionZones 5 # NONE # # # #
Start Time: Wed Apr 13 10:38:26 2016
Running script CalculatePredictionZones...
Executing: CreateConstantRaster C:\Users\am4337\Documents\ArcGIS\Default.gdb\CreateConsta1 0 INTEGER 1 ""
Start Time: Wed Apr 13 10:38:28 2016
ERROR 999999: Error executing function.
Failed to execute (CreateConstantRaster).
Failed at Wed Apr 13 10:38:29 2016 (Elapsed Time: 0.33 seconds)
Completed script CalculatePredictionZones...
Failed to execute (CalculatePredictionZones).
Failed at Wed Apr 13 10:38:29 2016 (Elapsed Time: 3.27 seconds)

**Comment by allisonmuise** [comment]
@a517dogg 
I agree, [error code 999999](http://pro.arcgis.com/en/pro-app/tool-reference/tool-errors-and-warnings/999001-999999/tool-errors-and-warnings-999998-999999-999999.htm) is the source of MUCH frustration among both Esri users and employees! It is the catch-all GP message for when a tool fails for unknown reasons.

In this case, that message is being generated by the CreateConstantRaster GP tool that the script is calling. Can you share the query so I can try to troubleshoot/reproduce the error? Also, can you send a screenshot of the properties window for the feature class showing the extents of the feature class you are providing as input? The extents are the only values getting passed to that tool, but in the error message you provided the extents are listed as '1'

**Comment by a517dogg** [comment]
It was just a definition query that excluded all points. It was a leftover query looking for origin points, when I had reloaded the data and there weren't any points classified as origin yet.

**Comment by allisonmuise** [comment]
ok, thanks! I'll add a check to make sure there are features in the dataset.

**Comment by allisonmuise** [comment]
@a517dogg : Can you re-test this with the latest tools to verify that I've addressed the issue?

**Comment by a517dogg** [comment]
With the toolbox I downloaded yesterday, I put the following definition query on that excluded all points: RESCITY <> 'Naperville'

I ran these parameters:
![image](https://cloud.githubusercontent.com/assets/15637772/15074774/c176b21a-136e-11e6-9f37-5a07f4c19078.png)

I got this result:
Executing: CalculatePredictionZones Naperville_burglary_sample OFFENSE_DATE YESTERDAY 2000 1000 14 7 CUMULATIVE "\\rpdfs.cor.local\mcac$\MCAC Operations\Personal Folders\Martin\beta test ESRI" C:\Users\am4337\Desktop\ExampleData.gdb\PredictionZones 5 # NONE # # # #
Start Time: Fri May 06 09:41:15 2016
Running script CalculatePredictionZones...
Executing: CreateConstantRaster C:\Users\am4337\Documents\ArcGIS\Default.gdb\CreateConsta1 0 INTEGER 1 ""
Start Time: Fri May 06 09:41:22 2016
ERROR 999999: Error executing function.
Failed to execute (CreateConstantRaster).
Failed at Fri May 06 09:41:23 2016 (Elapsed Time: 0.38 seconds)
Completed script CalculatePredictionZones...
Failed to execute (CalculatePredictionZones).
Failed at Fri May 06 09:41:23 2016 (Elapsed Time: 7.69 seconds)

**Comment by allisonmuise** [comment]
@a517dogg : should be fixed in current tool. Please test!

**Comment by allisonmuise** [comment]
@a517dogg : hang on, put the check in the wrong tool...

**Comment by allisonmuise** [comment]
ok! NOW it's fixed!

**Comment by a517dogg** [comment]
Yup, now it passes a specific error code, insufficient features for processing. Also it's much quicker to return that error code.

Executing: CalculatePredictionZones Naperville_burglary_sample OFFENSE_DATE YESTERDAY 2000 1000 15 6 CUMULATIVE "\\rpdfs.cor.local\mcac$\MCAC Operations\Personal Folders\Martin\beta test ESRI" C:\Users\am4337\Desktop\ExampleData.gdb\PredictionZones 5 # NONE # # # #
Start Time: Fri May 06 16:48:38 2016
Running script CalculatePredictionZones...
Insufficient features for processing
Completed script CalculatePredictionZones...
Failed to execute (CalculatePredictionZones).
Failed at Fri May 06 16:48:39 2016 (Elapsed Time: 0.57 seconds)

**Comment by allisonmuise** [comment]
good stuff
