### ISSUE TITLE
Repeat and near repeat tool crashes with global name not defined error

### ISSUE THREAD

**Issue by HPDAnalyst** [Esri/crime-analysis-toolbox#64]
I tried both geodatabase and file database versions. both in network folder as well as local drive.

Using the build from 04/13, after putting the parameters, the tool crashes with error global name 'spatial_band_field' is not defined

![hpd_rep_nrrep_spatial_band_field_error](https://cloud.githubusercontent.com/assets/18291921/14508237/5651b5d4-017b-11e6-9a0d-b612f651bc67.jpg)
![hpd_rep_nrrep_settings](https://cloud.githubusercontent.com/assets/18291921/14508238/56607a74-017b-11e6-9d9d-2ab896e57a47.jpg)

**Comment by SCHNZP** [comment]
I've just had this too. A couple of lines are missing from the script for the classification in the latest update. Thanks to Allison's previous advice about adjusting the field names in the script I identified the following solution:

Open the script incident_classification.py in an editing software (it opened automatically in IDLE on my laptop, could also have used Notepad, but it only opens a command prompt screen on my work PC). Under # Added field names add the follow two lines:
spatial_band_field = "SPACEBAND"
temporal_band_field = "TIMEBAND"

**Comment by allisonmuise** [comment]
so weird! My copy still has those two lines. I don't know how that happened. Regardless, I just re-sync'd with GitHub. Either add the two lines @SCHNZP describes above, or re-download the ZIP and it should now work.

**Comment by allisonmuise** [comment]
Actually - I just checked and that error has been re-introduced. Give me 5 mins and then download!

**Comment by allisonmuise** [comment]
closing since there hasn't been any further reports of this issue
