### ISSUE TITLE
Connector lines longer than maximum bandwidth

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#65]
Testing the updated tool on the Naperville sample, same parameters: 500,1000,1500 ft, 7, 14, 21 days.

New connection appears longer than the maximum spatial bandwidth (green line without pink line underneath, measurement shown as thin black line) 
![image](https://cloud.githubusercontent.com/assets/18314779/14510594/50db2832-0226-11e6-889e-cb7c0ced0491.png)

Found another couple of examples:
 
![image](https://cloud.githubusercontent.com/assets/18314779/14510539/27fbca98-0226-11e6-9265-f36eae7943b5.png)

The results screen that popped up once the tool had run said something in green about different datums but I didn’t manage to capture it and it’s not appearing in the results window now (which also shows that it’s measuring in feet appropriately):
 
![image](https://cloud.githubusercontent.com/assets/18314779/14510544/2d708c34-0226-11e6-8588-47c2cefb5854.png)

(Of note this took 16 minutes to run on the Naperville sample which was previously around 4 minutes)

**Comment by allisonmuise** [comment]
Yup - roughly 50 of the points are now getting processed an extra 2-3 times to take care of the issues with no originator & missed connections. I'm looking into options for multi-threaded processing for the next release.

As for the length:
It's fuzzy, but it looks like you are seeing Planar measurements. The Near tool is using Geodesic which may account for the offset. You can check by changing the measurement type:
![2016-04-13 3-46-50 pm](https://cloud.githubusercontent.com/assets/2752195/14511892/9f7a70f2-018f-11e6-8e13-f45138f23743.png)

If there's still a discrepancy, another possibility is the coordinate systems. The message you saw was likely the 'The data you just added is in a coordinate system that's different than the data frame' message. If that's the case, your data may be being re-projected into a CS that has different accuracy in Naperville than the CS of the data. I'm not sure where the measure tool gets it's info from, but you could also try setting the data frame to use the same CS as the data to reduce any weirdness that may be going on there. To change the CS of the data frame: right-click the bold Layers title in the TOC > Properties > Coordinate System tab > click the little down arrow next to the globe icon to the right of the search box > Import > Choose your incident dataset

**Comment by SCHNZP** [comment]
Sorted by way of switching to geodesic measurement, thanks, so this can be closed.

**Comment by allisonmuise** [comment]
@SCHNZP 
great! I like these easy fixes ;)
