### ISSUE TITLE
repeat near repeat additional error - list index out of range

### ISSUE THREAD

**Issue by HPDAnalyst** [Esri/crime-analysis-toolbox#66]
I have used the newest build after the last script update which did fix the global name not defined but now having an issue with "list index out of range"

![hpd_rep_nrrep_list_index_out_of_range_error](https://cloud.githubusercontent.com/assets/18291921/14513230/779bfcb2-019a-11e6-9028-1be82f8de70e.jpg)

**Comment by allisonmuise** [comment]
non-repro per #70
