### ISSUE TITLE
Date format info/prompt/calendar for prediction zones tool

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#67]
For the Initial Processing Date would it be possible to (in order of preference):
- be able to pick a date from a pop up calendar 
- have the field pre-entered with a predefined date format/template
- have in the field label the date format ie dd-mm-yyyy

**Comment by SCHNZP** [comment]
oops I got that wrong yyyy-mm-dd.

**Comment by allisonmuise** [comment]
Of each of these, the closest I can come is to pre-populate with the most recent date from the dataset. We chose to originally go with YESTERDAY as the default because we thought it would be the most commonly used, but we'll revis this based on your feedback.

**Comment by SCHNZP** [comment]
That sounds like a good solution because in an operational setting if this is being used daily to produce daily deployment maps based off the most recent data, the most recent date from the dataset will usually be 'yesterday' anyway. I managed to bungle the date entry twice before getting the right format (short term memory fail!) so having that format pre-populated or prompted will be helpful.

**Comment by allisonmuise** [comment]
@SCHNZP we'll make sure to have this documented in the tool help as well as the solution help
