### ISSUE TITLE
Offences in prediction zones vs near repeats

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#69]
I would think that any offence that appears within a prediction zone should be classed as an NR, but that's not always the case. Example: prediction zones calculated based on initial processing date 11/3/16, spatial influence 500m, and temporal influence 5 days (ie offences from 11/3, 10/3, 9/3, 8/3, 7/3). An offence on 12/3/16 falls within a prediction zone but is not classed as a near repeat, and the zone is based on an offence on 7/3/16 which is not classed as an originator (based on the same 500m and 5 day parameters entered into the RNRC). To my mind the RNRC should class that offence on 12/3/16 as an NR as it was predicted by the prediction zone, meaning the RNRC should be looking at the same 5 days preceding the offence, so 12/13 = day 0, 11/3= day 1, 10/3 = day 2, 9/3 = day 3, 8/3 = day 4, 7/3 = day 5).

**Comment by SCHNZP** [comment]
Found an example in the Naperville dataset. Offence id 2010007184. If you run the RNRC with a temporal band of 21 days, and the prediction zones with 21 day spatial influence with initial processing date 11/6/16, this offence on 12/6/16 is within the prediction zone (it is an exact repeat spatially), but not classed as a repeat.

**Comment by allisonmuise** [comment]
ok - I see it. I suspect the tool is including the dates at both ends in the count which puts the difference between them at 22 days instead of 21. I'll look into this.

**Comment by HPDAnalyst** [comment]
Thanks


Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by allisonmuise** [comment]
@HPDAnalyst : Are you still seeing this issue?

**Comment by SCHNZP** [comment]
I just went to test this with the Naperville data but it failed:
![image](https://cloud.githubusercontent.com/assets/18314779/15163008/2bdad156-175a-11e6-9de4-99ed55e15990.png)
![image](https://cloud.githubusercontent.com/assets/18314779/15163013/309c4210-175a-11e6-98c2-14007424c209.png)

**Comment by allisonmuise** [comment]
@SCHNZP It looks like you're missing some of the arcrest files. Can you re-download the tools from github, re-extract the zip, and try running them again?

**Comment by SCHNZP** [comment]
ok I have done that but it's still coming up with the same error.

**Comment by allisonmuise** [comment]
@SCHNZP : I can't reproduce this message with any dataset, and the error message is stating that it can't find specific scripts that are part of arcrest (python module found in the scripts folder). I'm going to send you an email.

**Comment by allisonmuise** [comment]
error message resolved

**Comment by SCHNZP** [comment]
Thanks again for the session this morning. Having got the prediction zones tool back up and running I have tested it in relation to the original issue #69 and can confirm that Naperville offence  2010007184 is now classed as a repeat and within the prediction zone based on those same parameters as used above. So that confirms the fix to the tool to be consistent with the RNRC in terms of which dates it's counting.

**Comment by allisonmuise** [comment]
:+1:
