### ISSUE TITLE
Can't process datetime values

### ISSUE THREAD

**Issue by HPDAnalyst** [Esri/crime-analysis-toolbox#70]
The last error of List index out of range is no longer occurring after I rebooted the machine and replaced all of the folder that the tool is in,

I can run the Naperville data with no problems even though it takes about 2 minutes longer to process on my machine,

When trying to run our data set that includes date and time in the occur date field, the invalid sql statement used error comes up (Naperville data does not have time, only date). Is this by design to only accept the date format and not date/time format?

Thanks
![hpd_invalid_sql](https://cloud.githubusercontent.com/assets/18291921/14536417/201f213e-0227-11e6-906e-a25df674045b.jpg)

**Comment by allisonmuise** [comment]
Nope - this should work with datetimes. I'll look into this and let you know when a fix is available.

**Comment by HPDAnalyst** [comment]
Thanks


Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by allisonmuise** [comment]
@HPDAnalyst : I can't reproduce this issue on the latest version of this tool. Can you? If so, can you repro this on the same dataset you're sending me through Box?

**Comment by HPDAnalyst** [comment]
Ok,

Will try now,

Can you send me the box account?


Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by HPDAnalyst** [comment]
Used the new code and it is still same problem



Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by allisonmuise** [comment]
ok, good.
I'll take a look once we get Box set up

**Comment by allisonmuise** [comment]
@HPDAnalyst : My results (same for fgdb version of the data):

![2016-05-11 2-28-16 pm](https://cloud.githubusercontent.com/assets/2752195/15197158/bdb8962e-1784-11e6-882d-801557d6b5b3.png)

**Comment by HPDAnalyst** [comment]
How does it display on the map?



Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by allisonmuise** [comment]
points show up fine, and classifications look good. 
Still playing with the other issue. Sometimes I can repro, sometimes I can't.

**Comment by allisonmuise** [comment]
@HPDAnalyst : What version of ArcGIS are you using?

**Comment by HPDAnalyst** [comment]
Using arcgis 10.3.1

On a 64Bit Windows 7 workstation
Xeon W3670
12GB RAM



Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759
