### ISSUE TITLE
Invalid Parameters error for Prediction Zones

### ISSUE THREAD

**Issue by HPDAnalyst** [Esri/crime-analysis-toolbox#71]
I have left the values as close to the default as possible like the example with Naperville. Our default c:documents and settings is mapped to a network location (due to city requirements, I am sure other cities are similar). when I run the prediction zones, error invalid parameters comes up

![hpd_rep_pred_zones_settings](https://cloud.githubusercontent.com/assets/18291921/14618916/c9975066-0569-11e6-8b56-364d9a471913.jpg)
![hpd_invalid_parameters_error](https://cloud.githubusercontent.com/assets/18291921/14618919/cc918818-0569-11e6-851a-a5b65a5edc69.jpg)

**Comment by allisonmuise** [comment]
@HPDAnalyst 
several questions to help me fully understand this issue:

1) Does the path mentioned in the error message exist? In ArcCatalog (or ArcMap's Catalog window) can you navigate to the path C:\Documents and Settings\sfe\My Documents\ArcGIS\Default.gdb?
2) In your ArcGIS Environment settings, what is the scratch workspace? In ArcMap/Catalog, go to the Geoprocessing menu and open the Environments dialog. Is the Scratch Workspace the same path from the error message? 
3) If the path in 2 matches the path in 1 and that path doesn't exist, try setting a valid scratch workspace, and re-run the tool. Does that fix the problem?

**Comment by HPDAnalyst** [comment]
Allison,

The path actually exists BUT I do not have access to it, LOL. IT has it blocked for all users even though ArcGIS installs that as default scratch work space. They have all of our local Documents and setting located at a server location which is channeled through from C to the network location that is transparent to us (but I guess not for ArcGIS)

I have been running ArcGIS with that default location for quite some time but just got upgraded to ver 10.3.1 a few weeks ago so maybe it did something to the rights.

I have since changed the scratch workspace location and it seems like it is running,

This error is due to our environment, not due to tool

But when the Prediction tool is running the % completed hits 298%




You can close the error please

Thanks

Safa



Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by allisonmuise** [comment]
Oh good! Glad that fixed it. When you run tools manually you probably update the path to something you can access. I'm using that scratch workspace setting to store all the intermediate datasets. @WalterPotts  and I will make sure that this is listed as an Environment setting used by the tool to help others troubleshoot this issue if they come across it.

The 298% drives me crazy. I think it's because things are processing so fast that the core tools lose count of what number they are at. How would you rate this on a scale of mildly annoying to serious confusion or concern that the tool is working properly?

**Comment by BobBooth** [comment]
@allisonmuise - I noticed that % complete issue too. I'd like to see it fixed, it is just wrong.

**Comment by allisonmuise** [comment]
@BobBooth agreed. I haven't been able to reproduce it locally in a few quick tests which makes getting a fox from the core team more difficult. Unless it's having a major impact on the user experience, I'd like to push more investigation to v2 of the tools. I've tried overriding the messaging with my own, and all it does is add my messaging to the system messages and slow the tool to a crawl. If you've got suggestions for a quick fix, I'm all ears!

**Comment by BobBooth** [comment]
@allisonmuise I put together a package that should make it easy to repro. Sent via email. Looks like a core issue. I wouldn't hold up your work for it, but would be nice to know what's up.

**Comment by allisonmuise** [comment]
@BobBooth : agreed. I'll investigate further once this tool is out the door.

**Comment by allisonmuise** [comment]
messaging issue moved to #76
