### ISSUE TITLE
near repeat bug

### ISSUE THREAD

**Issue by a517dogg** [Esri/crime-analysis-toolbox#73]
Joe Silva at RPD and I have passed the near-repeat tools the same parameters on the Napierville example data. It worked on Joe's computer and has repeatedly failed with the same error message on my computer. Not sure why. The listed error message is "global name 'spatial_band_field' is not defined."
Arcmap 10.4, Arcinfo license, spatial analyst extension enabled.
![nearrepeatfail](https://cloud.githubusercontent.com/assets/15637772/14641975/9a426064-0616-11e6-979d-8cf53fd7f2e6.png)
![nearrepeatparameters](https://cloud.githubusercontent.com/assets/15637772/14641974/9a3f3178-0616-11e6-8280-0ac604d9a0a8.png)

**Comment by allisonmuise** [comment]
@a517dogg: Try downloading the tool again. There was a brief window when there was an issue that produced this message, but it has since been fixed.
#64
