### ISSUE TITLE
minor irritant

### ISSUE THREAD

**Issue by a517dogg** [Esri/crime-analysis-toolbox#74]
In both tools, the parameter titles are left-justified, but the parameters themselves are right-justified (other than the drop-downs). I personally find this annoying... it'd be nice to have everything left-justified, like most other toolboxes.

**Comment by allisonmuise** [comment]
@a517dogg Can you provide an example of another Esri GP tool that has everything left justified? I'm not coding the UI so I can't control this, but if there's an inconsistency I can investigate why.

**Comment by a517dogg** [comment]
For instance in the Create Space Time Cube tool:

![image](https://cloud.githubusercontent.com/assets/15637772/14686050/2c3b5360-0705-11e6-91e7-dc8522c9626a.png)

However the Kernel Density tool (the one I probably use the most) also has the same irritant... I've just never been able to complain to a developer before!

**Comment by allisonmuise** [comment]
haha ok :)
I'll look into this and see if I can at least find an explanation for the inconsistencies.

**Comment by allisonmuise** [comment]
@a517dogg : as best I can tell, string (text) parameters show their value left-aligned, and numeric parameters show their values right-aligned. Microsoft Excel does this, too, and it appears to be a standard:http://ux.stackexchange.com/questions/13795/is-there-a-standard-to-left-justify-text-and-right-justify-numeric-values
