### ISSUE TITLE
INCCLASS = NR or R but TIMEBAND = NULL

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#78]
Running the updated RNRC on the Naperville data...

Output:
![image](https://cloud.githubusercontent.com/assets/18314779/15036217/1bdadeb4-12e0-11e6-978f-2068bebe2048.png)
![image](https://cloud.githubusercontent.com/assets/18314779/15036222/282cd53c-12e0-11e6-8cae-eaa0c74a32e8.png)

Some offences are classified as N or NR but the TIMEBAND is NULL - surely every R/NR should have a timeband?
![image](https://cloud.githubusercontent.com/assets/18314779/15036265/b1865272-12e0-11e6-9011-14bede1d6579.png)

![image](https://cloud.githubusercontent.com/assets/18314779/15036270/b736c756-12e0-11e6-8d9c-f70cf31cb331.png)

**Comment by allisonmuise** [comment]
@SCHNZP : The tool no longer calculates the bands for the incident features because one incident may fall into several different space/time bands relative to other incidents.

**Comment by allisonmuise** [comment]
@SCHNZP : The bands are visible on the line features (as the maximum band size the connection fits into)

**Comment by SCHNZP** [comment]
Makes sense - will just have to symbolise the lines by temporal band rather than the points then. Thanks!

**Comment by allisonmuise** [comment]
you can also put a def query on the lines to see only a specific band (eg TIMEBAND <=7 AND SPACEBAND <=1500) and then use a combination of Select By Location and Create Feature Layer to create a view of the point feature class that only includes points that touch those lines
