### ISSUE TITLE
Connections featureclass: RPTDAYS and SPACEBAND switch and max vs min band

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#79]
I think the column headers/data fields are the wrong way round in the Connections output feature class as the RPTDAYS for the Naperville dataset are all 1500 and the SPACEBAND are variable 1 5 7 2 24 19 etc. Also, because all connections are within the maximum TIME and SPACE BANDS by definition, (hence all rows are 1500ft and 21 days in below screenshot) I wonder if it would be more useful for this to be the minimum they fall into (like when these attributes where included the Offence points feature class)? That would enable symbology of connections by minimum band, which I find useful.

![image](https://cloud.githubusercontent.com/assets/18314779/15061515/787808e0-138a-11e6-8da7-be8c8df3151f.png)

**Comment by allisonmuise** [comment]
@SCHNZP : Could you try again with the latest code? This was an issue a few days ago, but should be fixed in the current tool

**Comment by SCHNZP** [comment]
Latest code has separate columns for space/time band combinations so this is no longer an issue.
