### ISSUE TITLE
RNRC error: Field is not nullable

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#80]
Running the updated RNRC tool on an existing dataset that I had successfully run the previous versions on (including having cleaned existing RNRC output attributes from it), got this error. Also noted that the dataset has 720 records, although it says 693 processed.

![image](https://cloud.githubusercontent.com/assets/18314779/15063113/41a7289e-139b-11e6-9723-4aa00dd58c86.png)

**Comment by allisonmuise** [comment]
I am unable to reproduce either of these errors using the Naperville data, or any of our other text datasets.

Are there any features in your data that are within 1 map unit and 5 days of one another?

Are you getting the invalid count on the same run that is throwing this error, or another run that is completing successfully?

**Comment by SCHNZP** [comment]
I reran with this dataset which was a shp file and it reproduced the error. I then converted the shp to featureclass and it worked. This is consistent with what I found in relation to issue 81.

**Comment by SCHNZP** [comment]
Oh and there were 9 features within 1 map unit and 5 days in this dataset.

The counts and percentages look right (though higher than previous iterations of the tool e.g. 38% is now 45% within 500m and 5 days).

**Comment by allisonmuise** [comment]
The script was inserting a null value in a way that wasn't supported by shapefiles. I've changed the value used when a classification can't be assigned from None to an empty string ('')
This should work for both shapefiles and feature classes.

**Comment by SCHNZP** [comment]
Just confirming I have tested the latest script as at 13/5/16 on the shapefile that produced the nullable error previously and now works fine, thanks.

**Comment by allisonmuise** [comment]
great!
