### ISSUE TITLE
RNRC error: can't compare datetime.datetime to nonetype

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#81]
Running the RNRC on a new burglary dataset keeps returning this error despite various experiments as to formatting of date fields and file types to shp file from (xls/csv):
![image](https://cloud.githubusercontent.com/assets/18314779/15063222/61d35542-139c-11e6-83c3-86f391e793b9.png)

**Comment by allisonmuise** [comment]
@SCHNZP : Does every feature in that dataset have a valid date? Can you zip this dataset and email it to me? That error will be easier for me to handle if I can figure out exactly what's different about the record that's throwing it.

**Comment by SCHNZP** [comment]
Now this is odd: I changed that dataset from a featureclass to a shpfile before running the new tool on it. With the latest code and using each of the 3 date fields in that dataset it now produces the NOT NULLABLE error. I have sent you through the dataset by email. Then I ran the RNRC on the featureclass version and it has worked - no error!

**Comment by SCHNZP** [comment]
Had the datetime.datetime error recurr but found a fix - there was one row in the featureclass with all null values. Deleting that row solved it. Has happened for a couple of recently created datasets, not sure why it's inserting the extra blank row in them.

**Comment by allisonmuise** [comment]
update should check for valid date values when processing. If an invalid value is found, you should get a warning message about which feature was skipped and why, but the tool should continue with the next feature
